# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureflow',
            old_name='lecture_id',
            new_name='lecture',
        ),
        migrations.AlterField(
            model_name='lectureflow',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
