# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('term', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Instructor')], max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course.Course')),
                ('post_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_quiz', to='quiz.Quiz')),
                ('pre_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_quiz', to='quiz.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='courses', through='course.CourseMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
