# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='post_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_quiz', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='pre_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_quiz', to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='courses', through='course.CourseMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
