# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='lecture',
        ),
        migrations.AlterField(
            model_name='vote',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
