# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20170331_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturequestion',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
